### ISSUE TITLE
Published?

### ISSUE THREAD

**Issue by srid** [JonathanReeve/jonreeve.com-ema#2]
Hey Jonathan, 

I'm just curious if the Ema version is published anywhere? Do you need any further assistance with this project? I'm looking forward to adding your site to https://ema.srid.ca/showcase :-)

**Comment by JonathanReeve** [comment]
I'm making some progress. It's mostly just that I don't have much time to work on it, with my dissertation chapter deadline looming. Here are the things I still have to figure out how to do: 

- [ ] get feed link back in nav area
- [ ] get dates working again in posts
- [ ] fix permalinks so that they match the old format (Jekyll format) 
- [ ] fix citation processing

I'll probably get around to doing these sometime this month or so.

**Comment by JonathanReeve** [comment]
That sounds great. Especially if it simplifies the codebase a bit.

**Comment by srid** [comment]
Ema's released! https://srid.ca/ema-0.8

**Comment by JonathanReeve** [comment]
Sweet! I fixed citation processing, so I should be able to merge this into jonreeve.com soon. I'll try to find a way to merge this onto the existing jonreeve.com repo, next.

**Comment by JonathanReeve** [comment]
Published! I'm going to deprecate this repo now, in favor of [jonreeve.com](https://github.com/JonathanReeve/jonreeve.com).
